name: Push Nuget With Inputs

on:
  workflow_dispatch:
    inputs:
      project_name:
        description: 'Name of the project'
        required: true
        type: choice
        options: ['Ogu.Dal.Abstractions', 'Ogu.Dal.MongoDb', 'Ogu.Dal.Redis', 'Ogu.Dal.Sql']
      version_number:
        description: 'Version number of the package'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1

      - name: Build Project
        run: dotnet build --configuration Release

      - name: Create Release
        run: gh release create ${{ github.ref_name }} --title "Release ${{ github.ref_name }}" --notes "" --draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push NuGet package
        run: dotnet nuget push src/${{ github.event.inputs.project_name }}/bin/Release/${{ github.event.inputs.project_name }}.${{ github.event.inputs.version_number }}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
